/*
 * DO NOT EDIT THIS FILE.
 * Automatically generated from /home/RTDNdb-man/PIW/uploads/ccl/AELM/AELM_2_2.ccl at 16:51:06 16/08/21 by astephen
 * via program ccl4rtdn version 1 SU 21331
 * for the AELM system
 * RTDN ID version:- 488000002
 * RTDN version:- 2
 * aelmPkt metadata version:- 2
 */

#ifndef _belmPkt_H
#define _belmPkt_H

#include <stdrtdn.h>



/**
 * AELM RTDN packet.
 */

typedef struct {
    uint32 sequenceNo;
    uint32 sampleTime;
} belmPkt;

#define RTDN_belmPkt_PVC 488

#define RTDN_belmPkt_ID 488000002

#define RTDN_belmPkt_VERSION 2

#define BELM_belmPkt_METADATA 2

#define GET_RTDN_belmPkt_ID(p) ((p)->belmPkt_488000002)
#define SET_RTDN_belmPkt_ID(p) ((p)->belmPkt_488000002 = 488000002)
#define IS_RTDN_belmPkt_PKT(p) ((p)->belmPkt_488000002 == 488000002)

#endif /* _belmPkt_H */
