/*
 * DO NOT EDIT THIS FILE.
 * Automatically generated from /home/RTDNdb-man/PIW/uploads/ccl/KC1E/KC1E_5_7.ccl at 14:06:41 28/06/23 by agood
 * via program ccl4rtdn version 1 SU 21978
 * for the KC1E system
 * RTDN ID version:- 416000005
 * RTDN version:- 5
 * kc1e metadata version:- 7
 */

#ifndef _kc1e_H
#define _kc1e_H

#include <stdrtdn.h>



/**
 * KC1E equilibrium magnetics RTDN packet, with F78 2143 changes
 */

typedef struct {
    uint32 sequenceNo;
    uint32 sampleTime;
    float32 C2E_UPZE1;
    float32 C2E_UNZE1;
    float32 C2E_UPZE2;
    float32 C2E_UNZE2;
    float32 C2E_UPZE3;
    float32 C2E_UNZE3;
    float32 C2E_UPZE4;
    float32 C2E_UNZE4;
    float32 C2E_PPZ00;
    float32 C2E_PNZ00;
    float32 C2E_PPZ01;
    float32 C2E_PNZ01;
    float32 C2E_PPZ02;
    float32 C2E_PNZ02;
    float32 C2E_PPZ03;
    float32 C2E_PNZ03;
    float32 C2E_PPZ04;
    float32 C2E_PNZ04;
    float32 C2E_PPZ05;
    float32 C2E_PNZ05;
    float32 C2E_PPZ06;
    float32 C2E_PNZ06;
    float32 C2E_PPZ07;
    float32 C2E_PNZ07;
    float32 C2E_TPZZ1;
    float32 C2E_TNZZ1;
    float32 C2E_TPZZ2;
    float32 C2E_TNZZ2;
    float32 C2E_TPZZ3;
    float32 C2E_TNZZ3;
    float32 C2E_TPZZ4;
    float32 C2E_TNZZ4;
    float32 C2E_TPZZ5;
    float32 C2E_TNZZ5;
    float32 C2E_TPZZ6;
    float32 C2E_TNZZ6;
    float32 C2E_TPZZ7;
    float32 C2E_TNZZ7;
    float32 C2E_EFLZ1;
    float32 C2E_EFLZ2;
    float32 C2E_EFLZ3;
    float32 C2E_ECZ1V;
    float32 C2E_ECZ2V;
    float32 C2E_ECZ3V;
    float32 C2E_ECC4V;
    float32 C2E_ECC4R;
    float32 C2E_CZ01;
    float32 C2E_CZ02;
    float32 C2E_CZ03;
    float32 C2E_CZ04;
    float32 C2E_CZ05;
    float32 C2E_CZ06;
    float32 C2E_CZ07;
    float32 C2E_CZ08;
    float32 C2E_CZ09;
    float32 C2E_CZ10;
    float32 C2E_CZ11;
    float32 C2E_CZ12;
    float32 C2E_CZ13;
    float32 C2E_CZ14;
    float32 C2E_CZ15;
    float32 C2E_CZ16;
    float32 C2E_CZ17;
    float32 C2E_CZ18;
    float32 C2E_SZ01;
    float32 C2E_SZ02;
    float32 C2E_SZ03;
    float32 C2E_SZ04;
    float32 C2E_SZ05;
    float32 C2E_SZ06;
    float32 C2E_SZ07;
    float32 C2E_SZ08;
    float32 C2E_SZ09;
    float32 C2E_SZ10;
    float32 C2E_SZ11;
    float32 C2E_SZ12;
    float32 C2E_SZ13;
    float32 C2E_SZ14;
    float32 C2E_S7U;
    float32 C2E_S7L;
    float32 C2E_VS1E1;
    float32 C2E_VS1E2;
    float32 C2E_VS3E1;
    float32 C2E_VS3E2;
    float32 C2E_VS5E1;
    float32 C2E_VS5E2;
    float32 C2E_VS7E1;
    float32 C2E_VS7E2;
    float32 C2E_FLD2;
    float32 C2E_FLD3;
    float32 C2E_FL05;
    float32 C2E_FL11;
    float32 C2E_EHZ1V;
    float32 C2E_EHZ2V;
    float32 C2E_EHZ3V;
    float32 C2E_EHC4V;
    float32 C2E_EHC4R;
    float32 C2E_ITFOD;
    float32 C2E_ITFEV;
    float32 C2E_ID1;
    float32 C2E_ID2;
    float32 C2E_ID3;
    float32 C2E_ID4;
    float32 C2E_VLRRU;
    float32 C2E_VLRRL;
    float32 C2E_IPLA;
    float32 C2E_PVPM;
    float32 C2E_PRPM;
    uint32 kc1e_416000005;
} kc1e;

#define RTDN_kc1e_PVC 416

#define RTDN_kc1e_ID 416000005

#define RTDN_kc1e_VERSION 5

#define KC1E_kc1e_METADATA 7

#define GET_RTDN_kc1e_ID(p) ((p)->kc1e_416000005)
#define SET_RTDN_kc1e_ID(p) ((p)->kc1e_416000005 = 416000005)
#define IS_RTDN_kc1e_PKT(p) ((p)->kc1e_416000005 == 416000005)

#endif /* _kc1e_H */
