/*
 * DO NOT EDIT THIS FILE.
 * Automatically generated from /home/RTDNdb-man/PIW/uploads/ccl/RtgseEvents2/RtgseEvents2_1_1.ccl at 13:58:38 05/10/22 by agood
 * via program ccl4rtdn version 1 SU 21827
 * for the RTCC2 system
 * RTDN ID version:- 344000001
 * RTDN version:- 1
 * rtccEventPkt2 metadata version:- 1
 */

#ifndef _rtccEventPkt2_H
#define _rtccEventPkt2_H

#include <stdrtdn.h>


#define SE_N_EVENT_FIELDS 2	/* Number of RTCC event fields */
#define SE_N_RTCC_EVENTS (SE_N_EVENT_FIELDS * sizeof(BitField) * 8)	/* Number of RTCC event bits */

/**
 * RTCC2 experiment protection events
 */

typedef struct {
  UINT32 sequenceNo;
  UINT32 sampleTime;
  BitField status;	/* This system's RTPS status */
  BitField events[SE_N_EVENT_FIELDS];	/* RTGS-E RTCC-RTPS trigger bits */
  UINT32 rtccEventPkt2_344000001;
} rtccEventPkt2;

/*
 * Definitions for the "status" bitfield.
 */
#define SE_RTPS_STAT_MASK (((1<<16)-1)<<0)	/* Generic RTPS status bits */

/*
 * Definitions for the "events" bitfield.
 */

#define RTDN_rtccEventPkt2_PVC 344

#define RTDN_rtccEventPkt2_ID 344000001

#define RTDN_rtccEventPkt2_VERSION 1

#define RTCC2_rtccEventPkt2_METADATA 1

#define GET_RTDN_rtccEventPkt2_ID(p) ((p)->rtccEventPkt2_344000001)
#define SET_RTDN_rtccEventPkt2_ID(p) ((p)->rtccEventPkt2_344000001 = 344000001)
#define IS_RTDN_rtccEventPkt2_PKT(p) ((p)->rtccEventPkt2_344000001 == 344000001)

#endif /* _rtccEventPkt2_H */