/*
 * DO NOT EDIT THIS FILE.
 * Automatically generated from /home/RTDNdb-man/PIW/uploads/ccl/RtpsGeneralControl/RtpsGeneralControl_3_7.ccl at 09:06:27 26/04/18 by agood
 * via program ccl4rtdn version 1 SU 19986
 * for the RTPS system
 * RTDN ID version:- 511000003
 * RTDN version:- 3
 * RtpsGeneralControl metadata version:- 7
 */

#ifndef _RtpsGeneralControl_H
#define _RtpsGeneralControl_H

#include <stdrtdn.h>



/**
 * RTPS general control packet for miscellaneous systems.
 */

typedef struct {
  UINT32 sequenceNo;
  UINT32 sampleTime;
  BitField controlRequest;	/* RTPS control request */
  UINT32 jumpToTerminationTime;	/* ms, Jump to termination time in ms from PRE */
  UINT32 RtpsGeneralControl_511000003;
} RtpsGeneralControl;

/*
 * Definitions for the "controlRequest" bitfield.
 */
#define RTPS_NORMAL_MASK (1<<0)	/* 0=Normal, 1= RTPS control */
#define RTPS_SLOW_STOP_MASK (1<<1)	/* 1= RTPS Slow Stop requested */
#define RTPS_FAST_STOP_MASK (1<<2)	/* 1= RTPS Fast Stop requested */
#define RTPS_MHD_STOP_MASK (1<<3)	/* 1= RTPS MHD Stop requested */
#define RTPS_MHD2_STOP_MASK (1<<4)	/* 1= RTPS MHD2 Stop requested */
#define RTPS_MCHS_STOP_MASK (1<<5)	/* 1= RTPS MCHS Stop requested */
#define RTPS_DHS_STOP_MASK (1<<6)	/* 1= RTPS DHS Stop requested */
#define RTPS_MCDHS_STOP_MASK (1<<7)	/* 1= RTPS MCDHS Stop requested */
#define RTPS_MHDFST_STOP_MASK (1<<8)	/* 1= RTPS MHDFST Stop requested */
#define RTPS_SPARE2_STOP_MASK (1<<9)	/* 1= RTPS SPARE 2 Stop requested */
#define RTPS_SPARE3_STOP_MASK (1<<10)	/* 1= RTPS SPARE 3 Stop requested */
#define RTPS_JTT_STOP_MASK (1<<11)	/* 1= RTPS Jump to termination requested */
#define RTPS_MAIN_DISCHARGE_MASK (1<<12)	/* 1= Main Discharge */
#define RTPS_ALTSEQ_1_MASK (1<<13)	/* 1= Alternative Sequence 1 */
#define RTPS_ALTSEQ_2_MASK (1<<14)	/* 1= Alternative Sequence 2 */
#define RTPS_ALTSEQ_3_MASK (1<<15)	/* 1= Alternative Sequence 3 */
#define RTPS_ALTSEQ_4_MASK (1<<16)	/* 1= Alternative Sequence 4 */
#define RTPS_DISABLE_AELM_MASK (1<<31)	/* 0=AELM normal, 1=AELM stop */

#define RTDN_RtpsGeneralControl_PVC 511

#define RTDN_RtpsGeneralControl_ID 511000003

#define RTDN_RtpsGeneralControl_VERSION 3

#define RTPS_RtpsGeneralControl_METADATA 7

#define GET_RTDN_RtpsGeneralControl_ID(p) ((p)->RtpsGeneralControl_511000003)
#define SET_RTDN_RtpsGeneralControl_ID(p) ((p)->RtpsGeneralControl_511000003 = 511000003)
#define IS_RTDN_RtpsGeneralControl_PKT(p) ((p)->RtpsGeneralControl_511000003 == 511000003)

#endif /* _RtpsGeneralControl_H */