/*
 * DO NOT EDIT THIS FILE.
 * Automatically generated from by xMARTE at 2024-11-11 17:00:20.096446 by root
 * new_packet metadata version:- 1_0
 */

#ifndef _new_packet_H
#define _new_packet_H



/**
 * new_packet packet.
 */

typedef struct {
    uint32 new_field;
    uint32 new_field1;
    uint32 new_field2;
    uint32 new_field5;
} new_packet;

#endif /* _new_packet_H */
